### ISSUE TITLE
No success or fail?

### ISSUE THREAD

**Issue by paulxtiseo** [manuelbieh/jQuery-Geolocation#3]
Using this on my site at http://libationlookup.com. On FF on a Mac, if I click on "Update", but then refuse to allow the site to have my info (by selecting the "Not now" option), it doesn't seem to trigger either the success or error functions? I placed breakpoints on lines 248 and 274 and got no hits. I am in callback limbo! :)

IMO, shouldn't it trigger the error callback?

**Comment by koiyu** [comment]
One would think so, but it's an [almost-four-year-old Firefox feature](https://bugzilla.mozilla.org/show_bug.cgi?id=675533).

I actually came to here to see if this plugin would work around this issue, but, alas, it doesn't. It could be possible to wrap the error-callback to a some sort of a timeout and fake the error-trigger that way…
